### ISSUE TITLE
Document privileges required for Athena use

### ISSUE THREAD

**Issue by 0xdabbad00** [duo-labs/cloudtracker#30]
These are:
```
arn:aws:iam::aws:policy/AmazonAthenaFullAccess
```

and access to the bucket with the CloudTrail logs:
```
PolicyDocument:
            Version : '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
                - 's3:ListBucket'
              Resource: 
               - s3bucket/*
               - s3bucket
```
