### ISSUE TITLE
Support AWS Profile?

### ISSUE THREAD

**Issue by jychen7** [duo-labs/cloudtracker#54]
**Background**
aws cli support `--profile demo-account-1`, other than `default`
however, I didn't find config.yaml supports profile, how does it work for multiple accounts? If no such option yet, can we create a feature request? I am happy to help

https://github.com/duo-labs/cloudtracker/blob/51e3ec3d255894851337083d048d94d37ff4bfaf/config.yaml.demo#L8-L14

https://github.com/duo-labs/cloudtracker/blob/51e3ec3d255894851337083d048d94d37ff4bfaf/cloudtracker/datasources/athena.py#L199-L200

**Expect**

have profile in config
```
accounts:
  - name: demo
    id: 111111111111
    profile: demo-account-1
    iam: account-data/demo_iam.json
```
